services:
  - type: web
    name: nifty50-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
    rootDir: server

  - type: web
    name: nifty50-frontend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run preview -- --host 0.0.0.0 --port 8080
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
    rootDir: .
