services:
  - type: web
    name: nifty50-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_PATH
        value: /tmp/data.ab
    autoDeploy: true
    rootDir: server

  - type: web
    name: nifty50-frontend
    env: node
    plan: free
    # packageManager: npm
    buildCommand: bun install && bunx vite build
    startCommand: bunx vite preview -- --host 0.0.0.0 --port $PORT
    autoDeploy: true
    rootDir: .

